/**
 * Shared email design shell — DropMarket's one email look.
 *
 * Structure (modeled on the layout the owner approved, GameBoost-style):
 *   • Logo lockup ABOVE the card, on the page ground.
 *   • A single left-aligned "modal" card: 1px border, 14px radius.
 *   • Heading row: a small PNG icon inline to the LEFT of a Title Case heading.
 *   • Left-aligned body + bold inline labels.
 *   • Order emails add a game-logo thumbnail row (the item's GAME logo, not the
 *     item image — always loads, from /email or /games assets).
 *   • Centered primary button, then a divider + a quiet in-card footer line.
 *   • Legal/copyright line OUTSIDE the card at the very bottom.
 *
 * Icons are hosted PNGs (Gmail strips inline SVG) at /email-icons/<name>.png,
 * with a <name>-dark.png variant swapped in dark mode. Dark mode is handled with
 * a `prefers-color-scheme: dark` block (Apple Mail/iOS); the light design is
 * also built to survive Gmail's own forced-dark inversion.
 */

const FOREST = '#14432A'
const FOREST_2 = '#1B5E3A'
const LIME = '#A3E635'
const INK = '#1A1D19'
const INK_2 = '#5B6157'
const MUTED = '#8A9187'
const LINE = '#E4E5DE'
const IVORY = '#FAFAF7'
const CARD = '#FFFFFF'
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'

const FONT =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"

/**
 * Icon keys available in /public/email-icons (real Tabler icons; each has a
 * -dark.png variant too). Generated by scripts/gen-email-icons (Tabler outline
 * → forest/light PNG). Add a key here + to the generator to add an icon.
 */
export type EmailIcon =
  | 'sale' | 'confirm' | 'ordered' | 'paid' | 'delivered' | 'refunded' | 'payout'
  | 'message' | 'application' | 'review' | 'approved' | 'rejected' | 'info'
  | 'listinglive' | 'changes' | 'reset' | 'magic' | 'emailchange' | 'invite'
  | 'welcome' | 'founding' | 'notice' | 'star' | 'dispute'

export interface EmailShellOptions {
  /** Preheader — the grey preview line in the inbox list. */
  preview?: string
  /** Inline heading icon (PNG in /email-icons). Omit for no icon. */
  icon?: EmailIcon
  /** The heading — write it in Title Case. */
  heading: string
  /** Inner content HTML (built from the block helpers below). */
  body: string
}

/** Dark-mode CSS: swaps card/text/logo/icon for the dark ground (Apple/iOS). */
const DARK_STYLE = `
  @media (prefers-color-scheme: dark) {
    .dm-bg { background:#0d0f0c !important; }
    .dm-card { background:#12160f !important; border-color:#26301f !important; }
    .dm-h, .dm-strong { color:#f4f7ee !important; }
    .dm-body { color:#b6bdaa !important; }
    .dm-muted { color:#9aa38b !important; }
    .dm-brand { color:#ffffff !important; }
    .dm-brand-2 { color:${LIME} !important; }
    .dm-div { border-color:#232c1a !important; }
    .dm-thumb { background:#0d0f0c !important; border-color:#2a331f !important; }
    .dm-thumbrow { background:#171c12 !important; border-color:#2a331f !important; }
    .dm-btn { background:${LIME} !important; color:${FOREST} !important; }
    .dm-accent { color:${LIME} !important; }
    .dm-logo-light { display:inline-block !important; }
    .dm-logo-dark { display:none !important; }
    .dm-icon-light { display:none !important; }
    .dm-icon-dark { display:inline-block !important; }
  }`

/** Wrap content in the full branded email. */
export function emailShell({ preview, icon, heading, body }: EmailShellOptions): string {
  const iconHtml = icon
    ? `<img src="${APP_URL}/email-icons/${icon}.png" width="26" height="26" alt="" class="dm-icon-light" style="width:26px;height:26px;vertical-align:middle;margin-right:11px;">` +
      `<img src="${APP_URL}/email-icons/${icon}-dark.png" width="26" height="26" alt="" class="dm-icon-dark" style="width:26px;height:26px;vertical-align:middle;margin-right:11px;display:none;">`
    : ''

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="light dark">
  <meta name="supported-color-schemes" content="light dark">
  <style>${DARK_STYLE}</style>
</head>
<body class="dm-bg" style="font-family:${FONT};background-color:${IVORY};color:${INK};margin:0;padding:32px 16px;">
  ${preview ? `<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${preview}</div>` : ''}

  <!-- Logo OUTSIDE the card -->
  <div style="max-width:560px;margin:0 auto 20px;text-align:center;">
    <img src="${APP_URL}/brand/logo-mark-ink.png" width="30" height="30" alt="" class="dm-logo-dark" style="width:30px;height:30px;vertical-align:middle;margin-right:8px;">
    <img src="${APP_URL}/brand/logo-mark-lime.png" width="30" height="30" alt="" class="dm-logo-light" style="width:30px;height:30px;vertical-align:middle;margin-right:8px;display:none;">
    <span class="dm-brand" style="font-size:21px;font-weight:800;letter-spacing:-0.02em;color:${FOREST};vertical-align:middle;">Drop<span class="dm-brand-2" style="color:${FOREST_2};">Market</span></span>
  </div>

  <!-- Card -->
  <div class="dm-card" style="max-width:560px;margin:0 auto;background:${CARD};border:1px solid ${LINE};border-radius:14px;padding:34px 36px;">
    <div style="margin:0 0 18px;">
      ${iconHtml}<span class="dm-h" style="font-size:22px;font-weight:700;letter-spacing:-0.01em;color:${FOREST};vertical-align:middle;">${heading}</span>
    </div>
    ${body}
  </div>

  <!-- Legal OUTSIDE the card -->
  <div style="max-width:560px;margin:18px auto 0;text-align:center;">
    <p class="dm-muted" style="font-size:12px;color:#9aa093;margin:0;line-height:1.6;">&copy; 2026 DropMarket &middot; <a href="${APP_URL}/support" style="color:#9aa093;text-decoration:underline;">Support</a></p>
  </div>
</body>
</html>`
}

/** A left-aligned paragraph of body copy. */
export function emailText(html: string): string {
  return `<p class="dm-body" style="font-size:15px;line-height:1.6;color:${INK_2};margin:0 0 18px;">${html}</p>`
}

/** A bold-label detail line: "Label: value" (used like GameBoost's Delivery/Qty/Price). */
export function emailDetail(label: string, value: string): string {
  return `<p class="dm-body" style="font-size:14.5px;color:${INK_2};margin:0 0 9px;"><strong class="dm-strong" style="color:${INK};">${label}:</strong> ${value}</p>`
}

/** Same, but the value is emphasised in forest (for payouts/totals). */
export function emailDetailAccent(label: string, value: string): string {
  return `<p class="dm-body" style="font-size:14.5px;color:${INK_2};margin:0 0 9px;"><strong class="dm-strong" style="color:${INK};">${label}:</strong> <span class="dm-accent" style="color:${FOREST_2};font-weight:700;">${value}</span></p>`
}

/**
 * The item row for order emails — GAME LOGO thumbnail + item name + subline.
 * `gameLogoUrl` should be an absolute URL to the game's logo (e.g.
 * `${APP_URL}/games/sab.png`); pass a fallback when the game has none.
 */
export function emailItemRow(opts: {
  gameLogoUrl: string
  itemName: string
  subline: string
}): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:2px 0 22px;"><tr>
    <td class="dm-thumbrow" style="background:#F7F8F3;border:1px solid #E9EAE2;border-radius:11px;padding:12px 14px;">
      <table role="presentation" cellpadding="0" cellspacing="0"><tr>
        <td class="dm-thumb" style="width:46px;height:46px;border-radius:10px;background:${CARD};border:1px solid ${LINE};text-align:center;vertical-align:middle;">
          <img src="${opts.gameLogoUrl}" width="36" height="36" alt="" style="width:36px;height:36px;object-fit:contain;vertical-align:middle;">
        </td>
        <td style="padding-left:13px;vertical-align:middle;">
          <div class="dm-strong" style="font-family:${FONT};font-size:14px;font-weight:600;color:${INK};">${opts.itemName}</div>
          <div class="dm-muted" style="font-family:${FONT};font-size:12.5px;color:${MUTED};margin-top:1px;">${opts.subline}</div>
        </td>
      </tr></table>
    </td>
  </tr></table>`
}

/** The primary CTA button — CENTERED — plus a "button not working?" fallback line. */
export function emailButton(label: string, href: string): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:2px 0 0;"><tr><td align="center">
    <a href="${href}" class="dm-btn" style="display:inline-block;background:${FOREST};color:#ffffff;text-decoration:none;padding:13px 32px;border-radius:8px;font-weight:700;font-size:14.5px;">${label}</a>
  </td></tr></table>
  <p class="dm-muted" style="font-size:12px;line-height:1.6;color:${MUTED};text-align:center;margin:12px 0 0;">Button not working? <a href="${href}" class="dm-accent" style="color:${FOREST_2};font-weight:600;text-decoration:underline;">Open it here</a>.</p>`
}

/** A soft-tinted callout box (perks, a message, a reason). Title optional. */
export function emailBox(opts: { title?: string; html: string; accent?: boolean }): string {
  const bg = opts.accent ? 'rgba(163,230,53,0.10)' : '#F7F8F3'
  const border = opts.accent ? 'rgba(20,67,42,0.16)' : LINE
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:2px 0 20px;"><tr>
    <td class="dm-thumbrow" style="background:${bg};border:1px solid ${border};border-radius:11px;padding:16px 18px;">
      ${opts.title ? `<p style="margin:0 0 8px;font-family:${FONT};font-size:12px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:${FOREST_2};" class="dm-accent">${opts.title}</p>` : ''}
      <div class="dm-body" style="font-family:${FONT};font-size:14px;line-height:1.65;color:${INK_2};">${opts.html}</div>
    </td>
  </tr></table>`
}

/** The in-card divider + a quiet footer line (help/reassurance). */
export function emailFooterNote(html: string): string {
  return `<div class="dm-div" style="border-top:1px solid #EEEFE8;margin:24px 0 16px;"></div>
  <p class="dm-muted" style="font-size:13px;line-height:1.6;color:${MUTED};margin:0;">${html}</p>`
}

/** Resolve a game's logo URL for the item row (mirrors GAME_ICONS on the site). */
export function gameLogoUrl(slug: string | null | undefined): string {
  const map: Record<string, string> = {
    'steal-a-brainrot': 'sab', 'grow-a-garden': 'gag', 'grow-a-garden-2': 'gag',
    roblox: 'roblox', 'adopt-me': 'roblox', fortnite: 'fortnite', valorant: 'valorant',
    'league-of-legends': 'lol', cs2: 'cs2', 'genshin-impact': 'genshin',
    'call-of-duty': 'cod', 'gta-v': 'gta-v', 'gta-vi': 'gtavi', minecraft: 'minecraft',
    'apex-legends': 'apexlegends', pubg: 'pubg', 'free-fire': 'freefire',
    'escape-from-tarkov': 'escapefromtarkov', 'rainbow-six-siege': 'r6', fc25: 'fc25',
  }
  const file = (slug && map[slug]) || 'roblox' // neutral fallback
  return `${APP_URL}/games/${file}.png`
}

// ── Back-compat aliases (kept so existing emails compile after the redesign) ──

/** Legacy alias — a quiet centered line. Prefer emailFooterNote for closers. */
export function emailSubtle(html: string): string {
  return `<p class="dm-muted" style="font-size:12px;line-height:1.6;color:${MUTED};text-align:center;margin:12px 0 0;">${html}</p>`
}

/** Legacy label:value row (left label / right value). */
export function emailRow(label: string, value: string): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 8px;"><tr>
    <td class="dm-body" style="font-family:${FONT};font-size:14px;color:${INK_2};">${label}</td>
    <td class="dm-strong" style="font-family:${FONT};font-size:14px;font-weight:600;color:${INK};text-align:right;">${value}</td>
  </tr></table>`
}

/** Legacy order-summary box from [label,value] rows; last row can be emphasised. */
export function emailOrderSummary(rows: Array<[string, string]>, highlightLast = false): string {
  const inner = rows
    .map(([label, value], i) => {
      const emph = highlightLast && i === rows.length - 1
      const top = emph ? `border-top:1px solid ${LINE};padding-top:10px;` : ''
      const ls = emph ? `font-size:15px;font-weight:700;color:${FOREST_2};` : `font-size:14px;color:${INK_2};`
      const vs = emph ? `font-size:16px;font-weight:800;color:${FOREST_2};` : `font-size:14px;font-weight:600;color:${INK};`
      return `<tr>
        <td class="dm-body" style="font-family:${FONT};${ls}${top}padding-bottom:8px;">${label}</td>
        <td class="${emph ? 'dm-accent' : 'dm-strong'}" style="font-family:${FONT};${vs}${top}padding-bottom:8px;text-align:right;overflow-wrap:anywhere;">${value}</td>
      </tr>`
    })
    .join('')
  return emailBox({ html: `<table role="presentation" width="100%" cellpadding="0" cellspacing="0">${inner}</table>` })
}

export const EMAIL_TOKENS = { FOREST, FOREST_2, LIME, INK, INK_2, MUTED, LINE, IVORY, FONT, APP_URL }
