-- ============================================================
-- P2.3: Idempotency Keys for Payment Operations
-- Created: 2026-02-17
-- Purpose:
--   Prevent duplicate charges from:
--   - Double-clicks on "Pay" button
--   - Network retries
--   - Race conditions between browser tabs
--
-- Strategy:
--   - Client generates a UUID idempotency key before payment
--   - Key stored in `processed_operations` on first request
--   - Subsequent requests with same key return cached result
--   - Keys expire after 24 hours (Stripe-compatible window)
-- ============================================================

CREATE TABLE IF NOT EXISTS processed_operations (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Idempotency key — client-generated UUID, unique per operation type
  idempotency_key TEXT        NOT NULL,
  -- The type of operation (e.g. 'create_payment_intent', 'release_escrow')
  operation_type  TEXT        NOT NULL,
  -- The user who initiated the operation (nullable for guest checkout)
  user_id         UUID        REFERENCES profiles(id) ON DELETE SET NULL,
  -- HTTP status code of the first successful response
  response_status INTEGER     NOT NULL DEFAULT 200,
  -- The response body (JSON) — returned on duplicate requests
  response_body   JSONB,
  -- The actual order/payment created (for quick lookup)
  related_order_id UUID       REFERENCES orders(id) ON DELETE SET NULL,
  -- When this record was created and when it expires
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Keys expire after 24 hours (align with Stripe's idempotency window)
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  -- Composite unique: same key can only be used once per operation type
  CONSTRAINT uq_idempotency_key_per_type UNIQUE (idempotency_key, operation_type)
);

-- Index for fast lookups by key + type
CREATE INDEX IF NOT EXISTS idx_processed_ops_key_type
  ON processed_operations (idempotency_key, operation_type);

-- Index for cleanup job (expired records)
CREATE INDEX IF NOT EXISTS idx_processed_ops_expires
  ON processed_operations (expires_at);

-- Index for user-scoped lookups
CREATE INDEX IF NOT EXISTS idx_processed_ops_user
  ON processed_operations (user_id)
  WHERE user_id IS NOT NULL;

-- ─── RLS ──────────────────────────────────────────────────────

ALTER TABLE processed_operations ENABLE ROW LEVEL SECURITY;

-- Only service_role (server-side code) can read/write — no client access
-- Authenticated users cannot read or write directly
DROP POLICY IF EXISTS "No direct client access to processed_operations" ON processed_operations;
CREATE POLICY "No direct client access to processed_operations"
  ON processed_operations
  FOR ALL
  TO authenticated
  USING (false);

-- ─── Cleanup function (called by cron) ───────────────────────

CREATE OR REPLACE FUNCTION cleanup_expired_idempotency_keys()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM processed_operations
  WHERE expires_at < NOW();

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$;

COMMENT ON TABLE processed_operations
  IS 'P2.3: Idempotency store. Prevents duplicate payment operations. Keys expire after 24h.';

COMMENT ON COLUMN processed_operations.idempotency_key
  IS 'UUID generated by the client before initiating a payment. Must be unique per operation_type.';

COMMENT ON COLUMN processed_operations.response_body
  IS 'Cached response returned to duplicate requests (same idempotency_key + operation_type).';
